### ISSUE TITLE
GOMPLATE_(LEFT|RIGHT)_DELIM environment variables are ignored

### ISSUE THREAD

**Issue by brianmori** [hairyhenderson/gomplate#1018]
Hello,

I believe I have found an issue in the release 3.8.0 when overriding the delimeters with environment variables

**Subject of the issue**
gomplate uses by default these template delimeters {{ and }}
It is necessary to override them because Helm uses the same delimeters

https://docs.gomplate.ca/usage/#overriding-the-template-delimiters

**Your environment**
gomplate version 3.8.0

**Steps to reproduce**

export GOMPLATE_LEFT_DELIM=(( GOMPLATE_LEFT_DELIM=))
export MY_VAR=ciao

$ gomplate -i 'fail: (( .Env.MY_VAR ))' 

**Expected behaviour**
ciao

**Actual behaviour**
((.Env.HOME))

**Comment by hairyhenderson** [comment]
@brianmori Thanks for logging this.

Indeed, using environment variables does not work:

```console
$ GOMPLATE_LEFT_DELIM='((' GOMPLATE_RIGHT_DELIM='))' gomplate -i 'fail: (( .Env.MY_VAR ))'
fail: (( .Env.MY_VAR ))
```

(note that `((` and `))` should be surrounded by quotes since they'd otherwise be interpreted by the shell)

However, using the `--left-delim`/`--right-delim` arguments works:

```console
$ gomplate --left-delim='((' --right-delim='))' -i 'fail: (( .Env.MY_VAR ))'
fail: ciao
```

Thanks for finding this bug, and sorry for the inconvenience!  As a workaround, you can use the flags. I'll fix this soon!

_(also note that in your report you typed `GOMPLATE_LEFT_DELIM` instead of `GOMPLATE_RIGHT_DELIM`, but that was clearly just a typo)_
