### ISSUE TITLE
gomplate -c .=root.yaml -c leaf=leaf.yaml ignores leaf.yaml completely.

### ISSUE THREAD

**Issue by pmorch** [hairyhenderson/gomplate#1073]
I have a `root.yaml` that I intend for "most" of the settings, but I want to set a single entry in the root from `leaf.yaml`.  So if I have:

`root.yaml`:

```yaml
rootA: a
rootB: b
```

and `leaf.yaml`:

```yaml
a: 1
b: 2
```

I want it to behave as:

```yaml
rootA: a
rootB: b
leaf:
  a: 1
  b: 2
```

Given `template.txt`:

```
rootA is {{ .rootA }}
leaf.a   {{ .leaf.a }}
```

I then expect that running this:

```
gomplate -c .=root.yaml -c leaf=leaf.yaml -f template.txt
```

Should result in this output:

```
rootA  is a
leaf.a is 1
```

But instead I get:
```
rootA  is a
leaf.a   
18:00:34 FTL  error="template: template.txt:2:17: executing \"template.txt\" at <.leaf.a>: map has no entry for key \"leaf\""
```

I've tried swapping the order of the `-c` params, but it seems no matter what I do, the `-c leaf=leaf.yaml` is ignored.

Workaround using `yq`: Pre-merge the leaf into `root.yaml` producing a temporary `combined.yaml` as so:

```bash
$ yq eval-all 'select(fileIndex == 0).leaf = select(fileIndex == 1) | select(fileIndex==0)' root.yaml leaf.yaml | tee combined.yaml
rootA: a
rootB: b
leaf:
  a: 1
  b: 2
$ gomplate -c .=combined.yaml -f template.txt
rootA  is a
leaf.a is 1

```
It would be great not to need `yq` and a temporary file for this, though.

**Comment by hairyhenderson** [comment]
Thanks for logging this, @pmorch.

I think you might be able to accomplish what you're looking for with a [`merge` datasource](https://docs.gomplate.ca/datasources/#using-merge-datasources). You'll probably need to restructure the `leaf.yaml` file so that it's a straight merge though.

In theory, something like this should work:

```console
$ gomplate -c .=merge:root.yaml|leaf.yaml ...
```

Otherwise, setting the root context and then setting another context has undefined behaviour. I should probably document that or add some validation to make sure that `.` is never used in conjunction with another context or datasource.

**Comment by pmorch** [comment]
Thank you for answering, Dave.

Yeah, I guess one *could* use a `merge` datasource. But the fact that I'll need to restructure it, puts a constraint on `leaf.yaml` that I won't be able to honor, so I would have to use an external tool like `yq` anyway. And then I might as well stick with the workaround I already have.

> Otherwise, setting the root context and then setting another context has undefined behaviour. I should probably document that or add some validation to make sure that . is never used in conjunction with another context or datasource.

I guess what I'm asking is for this to have defined behavior as I suggested. And I am well aware there can be 1000 implementation reasons why that is not feasible. So let's consider this an improvement suggestion, that you have declined to offer and leave it at that. At least now, people have a chance of finding this issue and seeing the `yq`-based workaround.

And my itch has been scratched albeit at the expense of another dependency, `yq`.

Cheers

**Comment by hairyhenderson** [comment]
> But the fact that I'll need to restructure it, puts a constraint on `leaf.yaml` that I won't be able to honor, so I would have to use an external tool like `yq` anyway.

Obviously I don't know your specific use-case, but given the sample you provided, simply shifting everything right and throwing a new root element doesn't seem like a big deal to me.

> And I am well aware there can be 1000 implementation reasons why that is not feasible.

I think you misunderstand - my reason for not supporting mixing `.` with other datasources isn't because it's hard to implement.

If I were to automatically merge datasources like this, a whole new range of issues would crop up, like what happens when `.` is defined _after_ another datasource? And, how should merging be done when the root context already contains an element with the same name as the additional datasource?

Ultimately, this is why `merge` datasources exist. When you use multiple datasources, they should be usable in isolation, without affecting each other.

**Comment by pmorch** [comment]
> Obviously I don't know your specific use-case, but given the sample you provided, simply shifting everything right and throwing a new root element doesn't seem like a big deal to me.

`leaf.yaml` comes from another source and is used for other things also, and isn't "shifted right" at the source. Sure it is easy enough to do with yq, but then so is working around this issue entirely.

> If I were to automatically merge datasources like this, a whole new range of issues would crop up, like what happens when . is defined after another datasource? And, how should merging be done when the root context already contains an element with the same name as the additional datasource?

:-)

Well defined semantics are necessary. That is true also now. This very issue is a symptom that it currently isn't well-defined. The semantics currently seem to be

* If you specify `-c .=URL` then it wins. All other `-c` parameters are ignored.

That is one way of defining it. I would suggest instead:

* Order matters. When specifying a `-c alias=URL` the alias overwrites the entire node specified by `alias` regardless of what it contained before.
    * So `-c .=root.yaml -c leaf=leaf.yaml` means that `.leaf` comes 100% from leaf.yaml regardless of what may or may not have been in `root.yaml` in the `.leaf` node.
    * Likewise for `-c some.path=path.yaml -c some.path.leaf=leaf.yaml` (I don't know if that is even possible)
* If you specify a more specific alias first and then afterwards a less specific alias, as in `-c leaf=leaf.yaml -c .=root.yaml` then `root.yaml` overwrites the root node in its entirety and the first `-c leaf=leaf.yaml` is effectively ignored.
* If you want to "mix" the content of `.leaf` node from `root.yaml` and from `leaf.yaml`, use a `merge` datasource.

The existing definition has the implication that if you have `-c .=URL` then all other `-c` parameters are ignored. My suggestion allows for functionality that was not possible before, in a well-defined way.

But hey, you've thought about this for much longer than I... ;-)

And my itch can be scratched with `yq`. I'd just rather prefer not to have `yq` as a dependency also.
