### ISSUE TITLE
alias with Docker Install > `gomplate --version` is not working/existing anymore

### ISSUE THREAD

**Issue by adriens** [hairyhenderson/gomplate#1203]
# Context

The alias with docker install is very convenient, but it seems like the `gomplate --version` is not working properly.

It looks like the `--version` has disappeared from the Docker distribution.

# Steps to reproduce

1. Open a brand new bash session : go to https://www.katacoda.com/courses/ubuntu/playground
2. Create the alias : 
```
alias gomplate='docker run hairyhenderson/gomplate'
```
3. Call `gomplate` help : `gomplate --help`
4. See that the `-v, --version` have disappeared
5. Call the `gomplate -v` command and get the error : 
```
$ gomplate -v
Error: unknown shorthand flag: 'v' in -v
```

This does not seem to match the official documentation : https://docs.gomplate.ca/installing/, see #1202 

![image](https://user-images.githubusercontent.com/5235127/131956772-76679593-7adb-4900-bb31-cdfce8963cbe.png)

**Comment by hairyhenderson** [comment]
Hmm... This works with the latest stable image:

```console
$ alias gomplate='docker run hairyhenderson/gomplate:v3.9.0'
$ gomplate --version
Unable to find image 'hairyhenderson/gomplate:v3.9.0' locally
v3.9.0: Pulling from hairyhenderson/gomplate
2b2db51c9855: Pull complete
737429efaa9c: Pull complete
Digest: sha256:a877a2068f2a1b120557e5cf05d2c8ea92a2267e12a1ed87d899e3771c44bbc0
Status: Downloaded newer image for hairyhenderson/gomplate:v3.9.0
gomplate version 3.9.0
```

Also `hairyhenderson/gomplate:stable` can be used.

The `latest` tag is created from whatever's in `master`, but the build expects there to be tag to version from, so I'm guessing that's why it's not working?

When I compile the latest from `master` locally, I do see a version being reported:

```console
$ bin/gomplate -v
gomplate version 3.9.0
```

This is obviously wrong (since I'm not on the v3.9.0 tag), but at least it's not an error. 🤷‍♂️

To fix this in the docs I think the best approach is to add the `:stable` tag to that image.

**Comment by adriens** [comment]
# Tests summarized

👎 `alias gomplate='docker run hairyhenderson/gomplate:latest'`
👍 `alias gomplate='docker run hairyhenderson/gomplate:stable'`
👍 `alias gomplate='docker run hairyhenderson/gomplate:v3.9.0'`

> To fix this in the docs I think the best approach is to add the :stable tag to that image.

Definitely agree 😺 

![image](https://user-images.githubusercontent.com/5235127/132107585-a086462b-34b0-42d9-82dd-ba3db08a93f6.png)
