### ISSUE TITLE
Error parsing CONSUL_HTTP_ADDR address

### ISSUE THREAD

**Issue by cofiem** [hairyhenderson/gomplate#1209]
gomplate version: 3.9.0

### Expected:

Running this command should successfully render the template.

env var: `CONSUL_HTTP_ADDR=127.0.0.1:8501` (which is valid as per [consul docs](https://www.consul.io/commands#consul_http_addr))

```
gomplate -d consul=consul+https://localhost:8501/foo -i '{{ ds "consul" }}'
```

### Actual:

Fails with error:

> ERR  error="template: <arg>:1:3: executing \"<arg>\" at <ds \"consul\">: error calling ds: Couldn't read datasource 'consul': invalid URL '127.0.0.1:8501' in CONSUL_HTTP_ADDR: parse \"127.0.0.1:8501\": first path segment in URL cannot contain colon"

### Additional info

This looks like it is due to `url.Parse` treating `127.0.0.1:8501` as a relative url at [line 82 in consul.go](https://github.com/hairyhenderson/gomplate/blob/master/libkv/consul.go#L82).
This might be an instance of [this issue](https://github.com/golang/go/issues/19297).

Is there a suggested workaround /fix for this? I guess the most obvious is to add the optional scheme to the `CONSUL_HTTP_ADDR` env var?

**Comment by hairyhenderson** [comment]
Hmm... The [gomplate docs](https://docs.gomplate.ca/datasources/#using-consul-datasources) implies that environment variable is a URL, I'm not sure I was aware that the consul package also understood that env var!

What's also concerning to me is that it looks like you're specifying the consul server address in both the env var _and_ on the `-d` flag, and gomplate _should_ use the `-d` value rather than the env var.

So there are two bugs here unfortunately. I'll take a look at these soon. FYI I'm gearing up to release gomplate 3.10.0 soon, and I'll make sure to get this fixed in that release 😉

As for workaround - you should be able to simply omit `CONSUL_HTTP_ADDR` entirely. Or setting the schema on `CONSUL_HTTP_ADDR` as well.
