### ISSUE TITLE
Index function doesn't throw error if key doesn't exist

### ISSUE THREAD

**Issue by veera-chenna** [hairyhenderson/gomplate#1362]
With `.` operator, in case of missing key template rendering will fail with an error. But for a map with keys containing characters other than (a-z,A-Z,_,1-9) we started using the `index` function and `index` function is not throwing any error in case of a missing key. In case of missing key it just gives `<no value>` as output. Is there a way to throw error in case of a missing key with `index` function?

We found that there is a function `test.Required`, but this will fail even if the key exists with empty string. In my case it should fail only if the key is missing from the map. Can someone please help on this?

**Comment by hairyhenderson** [comment]
The reason this is happening is because `index` behaves quite differently from accessing a value through the `.` operator. To get around this, you can use the [`coll.Has`](https://docs.gomplate.ca/functions/coll/#coll-has) function.

----

For a bit more background, the `.` behaviour is controlled in code by [the `missingkey` option](https://pkg.go.dev/text/template#Template.Option). In gomplate, it's set it to `error` (i.e. stop template execution immediately with an error), but that has no effect on the `index` function, which behaves like the following in Go:

```go
v := myMap["some key"]
```

if there is no "some key" key, `v` will be assigned the zero value for the type `myMap` contains. For a `string` it would just be `""`, but for an `interface{}` or `any` type, the zero value renders as `<no value>` - that's why you're seeing what you're seeing.

I hope this explanation makes sense, even though the behaviour may not be ideal!

I'm going to close the issue now as I believe it's been answered, but feel free to re-open if you feel there's a bug that needs to be fixed - or start a [discussion](https://github.com/hairyhenderson/gomplate/discussions) if you want to discuss further!
