### ISSUE TITLE
Ability to join list of items into string with separator

### ISSUE THREAD

**Issue by alexandrem** [hairyhenderson/gomplate#143]
Something missing in the string functions is to be able to do a traditional join to make a string out of a list of items with a defined delimiter character.

```yaml
nameservers:
  - "8.8.8.8"
  - "8.8.4.4"
```
Template:
```
{{ (datasource "config").nameservers | join " " }}
```

output => "8.8.8.8 8.8.4.4"

**Comment by hairyhenderson** [comment]
@alexandrem thanks for taking the time to log this!

There is a `join` function, but I seem to have missed documenting it 🤦‍♂️. It unfortunately won't work in a pipeline like that (mostly because I didn't think about that usage, and instead chose to follow `strings.Join`'s signature more literally).

But you can use it like:

```console
$  gomplate -i '{{ $a := `[1, 2, 3]` | jsonArray }}{{ join $a "-" }}'
1-2-3
```

So your template could look like:

```go
{{ join (datasource "config").nameservers " " }}
```

I've documented it in 8a45646 just now.

**Comment by alexandrem** [comment]
Great thanks :)
