### ISSUE TITLE
[bug]: The yaml data source lost the ability to read the override

### ISSUE THREAD

**Issue by MatthiasDesrumaux** [hairyhenderson/gomplate#1441]
## Inputs

I got this data source file:

```yaml
php:
  memory: -1
  <<:
    memory: 1024
```

I has this template where php data source is the file above:

```ini
{{- $options := ds "php" -}}
memory_limit={{ $options.php.memory }}K
```

## Error

I got this with the latest stable:

```ini
memory_limit=-1K
```

## Expected

I got this with the 3.10 version:

```ini
memory_limit=1024K
```

**Comment by hairyhenderson** [comment]
Hi @MatthiasDesrumaux, thanks for reporting this.

According to this YAML 1.2 parser, `-1` is the correct value: https://yaml-online-parser.appspot.com/?yaml=php%3A%0A%20%20memory%3A%20-1%0A%20%20%3C%3C%3A%0A%20%20%20%20memory%3A%201024&type=canonical_yaml

I'm not sure I've not used `<<` in YAML before, and I can't find any references in the [YAML spec](https://yaml.org/spec/1.2.2/). With some digging, I've found that it's part of a draft spec called [Merge Key Language-Independent Type for YAML 1.1](https://yaml.org/type/merge.html). Either way, it's not part of the official current spec so it's likely that different parsers will interpret it slightly differently.

As to why the behaviour has changed, it's likely due to a bug fix in [`gopkg.in/yaml.v3`](https://github.com/go-yaml/yaml). 

Given that the current behaviour matches the PyYAML behaviour (as used in the above-linked YAML parser) I'm inclined to say that this is probably not a bug, but the correct behaviour.

If you disagree and think that this is indeed a bug in both PyYAML and the `gopkg.in/yaml.v3` parser, please file bugs with them first 🙂
