### ISSUE TITLE
CVE-2022-32149

### ISSUE THREAD

**Issue by xoxys** [hairyhenderson/gomplate#1533]
Sorry to bother you again, I've seen you have updated the affected dependency `golang.org/x/text` in the default branch already. Would it be possible to tag a new release for this? Thanks a lot!

Background: https://avd.aquasec.com/nvd/cve-2022-32149

**Comment by hairyhenderson** [comment]
@xoxys gomplate isn't vulnerable to this particular CVE because it doesn't serve HTTP connections, and so has no need to ever parse `Accept-Language` headers. Also the particular issue is really only relevant to long-running multi-user daemons, whereas gomplate is a short-running CLI.

I don't see a strong need to make a new release just for this - can you simply add an exception to your scanning tooling instead?

**Comment by xoxys** [comment]
Sure, thanks for your reply.
