### ISSUE TITLE
Release bump for golang 1.19.2 new public cves

### ISSUE THREAD

**Issue by twk3** [hairyhenderson/gomplate#1534]
Looking at the following which may be applicable:

- https://nvd.nist.gov/vuln/detail/CVE-2022-41715
- https://nvd.nist.gov/vuln/detail/CVE-2022-2879

Thanks!

**Comment by hairyhenderson** [comment]
Thanks @twk3.

gomplate is built with the latest Go versions in CI, so this can be considered fixed already, however the current release (3.11.3) is not yet built with that.

Here's my assessment of these vulnerabilities:

### CVE-2022-41715

> Programs which compile regular expressions from untrusted sources may be vulnerable to memory exhaustion or denial of service.

IMO this does not present much of an impact to gomplate, as it is not at all designed to accept untrusted input. If a regular expression _is_ provided to gomplate which exploits this vulnerability the worst impact would likely be an out-of-memory exception and crash of gomplate. And the onus is on the user to provide templates with trusted input (including non-pathological regular expressions).

### CVE-2022-2879

> [...] A maliciously crafted archive could cause Read to allocate unbounded amounts of memory, potentially causing resource exhaustion or panics.

Unfortunately it's not clear from the description, but this vulnerability is limited to tar archives (specifically, using the `archive/tar` stdlib package). Because gomplate doesn't interact with tar archives at all at the moment, there's no impact from this one.

What you do with this information is up to you - personally I would recommend explicitly ignoring these CVEs for now, so your scanning tooling can pass.

I haven't been planning on releasing another gomplate v3.11.x release, and instead have been focusing my (very limited) spare time on getting v4 ready for release.

Another option would be for you to compile gomplate yourself with Go 1.19.2 and use those binaries instead.

**Comment by lrsy** [comment]
Hi,

What about this one https://nvd.nist.gov/vuln/detail/CVE-2022-32149, which is also flagged as a HIGH security vulnerability by scanners?

Thanks

**Comment by hairyhenderson** [comment]
@lrsy that's a vulnerability in the `ParseAcceptLanguage` method, which gomplate doesn't ever use. Also that's part of the `golang.org/x/text` module, not the Go standard library, so updating to Go 1.19.2 would make no difference.

Either way, `golang.org/x/text` has since been updated in gomplate's `main` branch.

**Comment by lrsy** [comment]
Hi,

Ok, understood. The golang.org/x/text module is actually the one that is flagged as vulnerability and would require update to v3.8.0 to have it fixed.

Thank you

**Comment by hairyhenderson** [comment]
@lrsy yup - and that's already updated in `main`

Given the amount of time it's taking me to roll out v4.0.0 maybe it'd be a good idea to release a rebuilt version of gomplate (3.11.4). However, I'm short on spare time these days!

**Comment by hairyhenderson** [comment]
https://github.com/hairyhenderson/gomplate/releases/tag/v3.11.4 is released now
