### ISSUE TITLE
Feature Request: Add jq support

### ISSUE THREAD

**Issue by ahochsteger** [hairyhenderson/gomplate#1584]
The [jq transformation language](https://stedolan.github.io/jq/manual/) using the [gojq library](https://github.com/itchyny/gojq) would be a great addition to gomplate to enable complex data processing that is often required.

**Proposed Usage:**
```
gomplate \
  -i '{{ .books | jq `[.works[]|{"title":.title,"authors":[.authors[].name],"published":.first_publish_year}]` }}' \
  -c books=https://openlibrary.org/subjects/fantasy.json
```

**Comment by hairyhenderson** [comment]
Hi @ahochsteger, thanks for filing this. I love jq, and occasionally find myself using it to pre-process data before feeding into gomplate, so this is a great idea!

**Comment by thesuperzapper** [comment]
@hairyhenderson I think your PR in https://github.com/hairyhenderson/gomplate/pull/1585 did not actually add the JQ function, because however I try and use it, it seems to be missing:

- if I try via its alias `jq` I get the error `function "jq" not defined"`
- if I try via the `coll.JQ` I get the error ` at <coll>: can't evaluate field JQ in type interface {}"`

**Comment by hairyhenderson** [comment]
@thesuperzapper what version of gomplate are you using? I don't think it made it into the 3.11.x releases...

**Comment by thesuperzapper** [comment]
@hairyhenderson ohh, I see, I was confused because I saw it [on the website](https://docs.gomplate.ca/functions/coll/), I am using `3.11.5`.

**Comment by hairyhenderson** [comment]
@thesuperzapper yeah - it's a pain 😢... I have #1697 to track working on fixing that 😓
