### ISSUE TITLE
implement `dig` function

### ISSUE THREAD

**Issue by thesuperzapper** [hairyhenderson/gomplate#1775]
## Problem

Currently, it's very painful to unpack fields from nested map objects when the presence of keys is unknown.

Right now, people have to resort to solutions like this:

```yaml
{{- if and (has .A "B") (has .A.B "C") (has .A.B.C "D") }}
  hello: {{ .A.B.C.D }}
{{- end }}
```

## Solution

We could implement a feature like [helm's `dig`](https://helm.sh/docs/chart_template_guide/function_list/#dig) (which I think comes from [sprig](https://masterminds.github.io/sprig/)).

__This would allow people to un-nest objects/dicts using:__

```yaml
dig "user" "role" "humanName" "guest" $dict
```

__For a `$dict` that looks like:__

```
{
  user: {
    role: {
      humanName: "curator"
    }
  }
}
```

## Related Issues:

- https://github.com/hairyhenderson/gomplate/issues/1497

**Comment by hairyhenderson** [comment]
I'm actually second-guessing whether this is necessary now.

A simple way to address this, with simpler (arguably) and more flexible syntax, is with the [`jq` (aka `coll.JQ`) function](https://docs.gomplate.ca/functions/coll/#colljq):

Here's an example:

_in.tmpl:_
```
{{ $m := dict "a" (dict "aa" (dict "aaa" 42)) "b" 2 -}}
$m is {{ printf "%#v" $m }}

a.aa.aaa:      {{ jq ".a.aa.aaa" $m }}
a.b (missing): {{ jq ".a.b" $m | default "missing item" }}
```

```console
$ gomplate -f in.tmpl
$m is map[string]interface {}{"a":map[string]interface {}{"aa":map[string]interface {}{"aaa":42}}, "b":2}

a.aa.aaa:      42
a.b (missing): missing item
```

It's much more flexible than `dig` because you can deal with arrays too (like `.a[5].b`).

Does that seem like a reasonable alternative? Can you think of a reason `dig` would be necessary instead?

**Comment by thesuperzapper** [comment]
@hairyhenderson that is what I tried at first, but it turns out that `coll.JQ` was not included in gomplate 3.

**Comment by hairyhenderson** [comment]
@thesuperzapper fair enough. Should we close this then, considering that JQ will be in v4?
