### ISSUE TITLE
Directory datasource

### ISSUE THREAD

**Issue by zealic** [hairyhenderson/gomplate#215]
A new feature *data.Directory*:

Datasource will recursive scan directory files, include:

* _*.json_
* _*.yaml_ or _*.yml_
* _*.toml_

## Example

Datasource directory

file: *config/message.json*
```json
{
  "welcome": "Hello World"
}
```

file: *config/person.yml*
```yaml
name: "Gomplate"
```

Shell code:
```shell
# Datasource need endwith slash
gomplate -d config=./config/ ...
```

Template:
```
{{ $config := (datasource "config") -}}
{{ $config.message.welcome }}, {{ $config.person.name }}!
```

OUTPUT:
```
Hello World, Gomplate!
```

**Comment by hairyhenderson** [comment]
@zealic Thanks for the feature request! This is indeed something I'd like to do.

A similar idea was put forward in #124, though in that one the datasource aliases were inferred based on filename, whereas I think I slightly prefer this proposed syntax.

I can start working on this soon, unless you were hoping to implement it?

**Comment by zealic** [comment]
I'm no plan to implement it for this time.

Thank you for your work.

I love gomplate ❤️ , it help me resolve many problems.

**Comment by hairyhenderson** [comment]
@zealic you're welcome! 😀

I'll see if I can find time to work on it soon. Thanks again for the request!

**Comment by hairyhenderson** [comment]
Fleshing out this idea in my head a bit more, I think the approach of using a trailing `/` is probably the correct one, and I think it turns out this can apply to more than just file-based datasources.

Here's how it could work with the various supported datasources:
- `aws+smp` - could use `GetParameters` to list parameters with a given prefix
- `boltdb` - could list all keys in a given bucket
- `consul` - could use `get-tree`
- `file` - would return a directory listing (much like `file.ReadDir`)
- `http` - n/a
- `stdin` - n/a
- `vault` - could use the `LIST` operation

It'd take some time to get here, though, and I think the natural place to start is with `file`. I think the big trick will be to come to a UX that's not too cumbersome to use.
