### ISSUE TITLE
Can we specify stdin as a datasource?

### ISSUE THREAD

**Issue by josdotso** [hairyhenderson/gomplate#230]
Use case example:

```
generates_some_yaml | gomplate --file template.yaml --datasource config=-
```

**Comment by hairyhenderson** [comment]
Hi @josdotso, thanks for the feature request! I think this sounds reasonable. I'll see what I can do!

**Comment by hairyhenderson** [comment]
@josdotso there's a hitch with your suggested syntax... `gomplate` decides how to parse a datasource based on either the file's MIME type, or file extension. When using `stdin`, obviously we lose that information.

How about providing a fake filename with a `stdin` URL scheme? Something like this:

```
generates_some_yaml | gomplate --file template.yaml --datasource config=stdin:///config.yaml
```

Another approach could be to allow setting/overriding the MIME type directly as a URL query parameter, like this:

```
generates_some_yaml | gomplate --file template.yaml --datasource config=stdin://?type=application/yaml
```

Obviously more verbose, though the same approach could be applied generally to other datasource types to allow overriding the MIME type... 🤔

I think there's still value in allowing `-`, if you're just going to `include` the data and don't need it to be parsed, but otherwise a type will be necessary for parsing.

**Comment by josdotso** [comment]
Thanks for the feedback!  

Any method would be fine with me.  I actually ran into the mime issue with a `something.yaml.tmp` that I rendered as a workaround.  I think the first example is my favorite of the two.

**Comment by hairyhenderson** [comment]
Ok! I like both approaches, and I may add the second as a more general flexibility thing... But for now I'll implement the first 😉
