### ISSUE TITLE
Question: Is there a template function to read in a file

### ISSUE THREAD

**Issue by pvdvreede** [hairyhenderson/gomplate#249]
Hi there,

I was wondering if there is a template function to read in the contents of a file into a string? I know this is what datasources are for but wanted to read in various files adhoc without having to change the cli command. eg I want to be able to read a file into a string and output the checksum to provoke a change of a deployment in kubernetes. It would be good to do this in place in the template rather than having to hide the file name in a datasource and then change or add more datasources if I wanted to read in more files.

Is this possible now? or in the future? 

Thanks.

**Comment by hairyhenderson** [comment]
@pvdvreede Thanks for logging this! There's currently no such function, but everything's _possible_ 😉

Can you explain your use-case a little more?

I wonder if piping the file in through `stdin` as a datasource would help? It's not in a release yet, but will come soon - see https://gomplate.hairyhenderson.ca/functions/data/#providing-datasources-on-standard-input-stdin for details.

**Comment by pvdvreede** [comment]
Thanks for replying @hairyhenderson.

The reason for the specific question is that I am writing a tool that under the hood shells out to gomplate to be able to add some extra functionality to creating Kubernetes manifest files see https://github.com/MYOB-Technology/kt.

One of the things that we need to do is in order to provoke a rolling deploy of a app whenever its configuration changes, we need to put a checksum of the config file in the deployment manifest to provoke the rolling deploy. So from one template we need to read in and checksum the contents of another template. See here for example: https://github.com/MYOB-Technology/kt/blob/master/example/templates/myapp.yaml#L17

At the moment I have solved it by dynamically creating the cli command to set each template (excluding the one that is being compiled) as a datasource with the filename as the key.

This seems to work quite well so my immediate need for this is now gone.

I thought maybe reading in files was not added to try and keep some purity or determinism for running gomplate, but note you have some `net` functions to pull out IPs and NS lookups so dont think that is an issue?

So I suppose aside from my use case above I dont really have any other immediate need other than it would be nice to reduce the complexity of my shelling out in the tool, and also make it easier to be able to separate out complex templating things into multiple files and then read them in to a template at compile time - AWS Cloudformation yaml templates with a separate userdata file that gets read in and put in the YAML might be another handy use case.

Thanks for the great work on the tool!

**Comment by hairyhenderson** [comment]
Thanks @pvdvreede - `kt` looks nifty! And the use-case makes sense.

> I thought maybe reading in files was not added to try and keep some purity or determinism for running gomplate, but note you have some net functions to pull out IPs and NS lookups so dont think that is an issue?

I've been _mildly_ reluctant to allow templates to access the filesytem (beyond datasources, that is), but to be honest I'd rather take a more pragmatic approach...

One idea that I had was to modify `datasource`/`ds` and `include` to try to resolve a file or URL if an alias can't be resolved, for example:

```
$ gomplate -i '{{ include "foo.txt"}}'
<contents of foo.txt>
$ gomplate -i '{{ (ds "https://example.com/bar.json").baz }}'
...
```

Or an alternative would be to have some function that can define a new datasource in the template, something like:

```
{{ data.Define "alias" "../../foo.yaml" }}
...
{{ (ds "alias").something }}
```

I do worry a bit about security aspects, as this means people need to be careful with untrusted templates, lest they open up a "template injection" attack. But there are already functions that could open up issues (`aws.EC2Dynamic` for example), so that particular Pandora's box is already open 😉

One other approach, and maybe to be combined with the ability to define datasources, would be a new `file` namespace, which could provide read-only functions like `file.Read`, `file.DirRead`, `file.Exists`, etc... But that may come _later_.

One line I'm not _super_ willing to cross yet, however, is providing support for shelling out from a template. That just feels messy IMO 😉.

**Comment by pvdvreede** [comment]
I agree with not allowing shelling out as that is a step too far.

Any of the options sound good for adding in file reading, however when I started to look to see if I could do it in Gomplate, the first place I went to was to look for a namespace with a function that would allow me to do it - so to me at least that would seem the most intuitive and explicit place to put them for a new user to look - where as making it implicit in `include` or `datasource` might make it harder for people to figure out how to do it.

**Comment by hairyhenderson** [comment]
@pvdvreede thanks for the feedback - it makes sense. I'll prioritize `file.Read` 👍

**Comment by pvdvreede** [comment]
many thanks!
