### ISSUE TITLE
Couple of ideas

### ISSUE THREAD

**Issue by nikolay-turpitko** [hairyhenderson/gomplate#343]
@hairyhenderson 

Hi! Nice project. If I knew about it when I started my own similar one, I'd save myself some time and trouble. There are only couple more things I'd like to see from the similar tool:

- Slim-like (or other lightweight) templates, I used `ace`, but their project seems not very active;
- Function for spelling numbers into words, I used `icu4c`, but it's a heavy compile dependency;
- Custom Go plugins to extend set of functions, available in templates;
- Probably, Go-like scriptlets within templates (simple ones for more convenient math);

Some of those ideas I partly implemented in my project (more accurately - 2 related projects). They are mostly hobby projects for my own use, so, not of a best quality. But feel free to take a look and borrow some ideas from them, if you like.

Idea with plugins I have not implemented yet, but it should be feasible. it should be possible to create general interface to discover functions in the custom Go libs, containing within particular folder (or some CLI flag may be used to provide folder path). Tool would enumerate files within folder, try to dynamically load it and invoke API to load map of functions from it. Probably, other things might be extracted into separate plugins like this. For example, `icu4c` is a heavy dependency and would be nice to have it like plugin. Experienced users would create their own Go packages with custom functions. Also, it'd be possible to leverage unix toolset via similar idea. For example, to invoke bash/awk/python functions.

This is only FYI, feel free to close this issue right away. I just don't know how to better and less intrusive contact you.

Ah, and links:
- https://github.com/nikolay-turpitko/x-go-templator
- https://github.com/nikolay-turpitko/structor/tree/master/funcs

**Comment by hairyhenderson** [comment]
Hi @nikolay-turpitko! Thanks for the contact - these are some good ideas!

Some of these ideas are ones I've contemplated before, so I'll share my opinions on these 😉

On using alternate template engines/syntaxes (such as `ace`) - this has been mentioned a few times I think, and I'm a bit wary of this, since it further confuses the usability. I like Go's `text/template` syntax and don't really see a big reason to support other syntaxes yet at the same time. _That being said,_ I definitely see the benefit of a slimmer syntax especially for HTML templating! I'm just not sure gomplate would be suited to this kind of thing. To be totally honest I have no idea what most gomplate users are using gomplate for - my assumption is mostly for config generation and the like.

On number-spelling functions - sure, absolutely! I'm not at all willing to bring cgo into the mix for that, though 😉. It feels like I've run into a similar pure-Go package for this, I just can't put my finger on it... 🤔

On plugins - this has come up in the past, though mostly in the context of slimming down the binary. I'm currently happy with the `slim` binary that's produced with UPX though. I'm not _opposed_ to plugins for extending functionality, but in general new functionality should just go into gomplate so everyone can benefit 😉

On "scriptlets" - I'm not sure what you mean by this, but I'm intrigued...

Again, thanks for taking the time to provide this feedback!

**Comment by hairyhenderson** [comment]
Thanks for the explanations, lots of great info there. Generating invoices is a really interesting use-case - and I can definitely see the potential there...

Lots of interesting stuff though, a lot to chew on. I'll think about a bunch of these concepts in the future!

> ...stores some result of calculation back into template context. Like you may put a map for variables into it and set some vaule in it with function and use this "variable" later in the template

This is definitely something I'm interested in. A while back I started sketching out some code to do this, but got distracted - I'll pick that back up sometime soon.

> Ah, and talking about Excel, I thought about using CSV/LiteDB/SQL as a datasource

I've been thinking about more database-oriented datasources - not totally sure about the best way to present those, but there may be a way that's simple enough for most use-cases.

Thank you for your good insights!
