### ISSUE TITLE
Overriding MIME Types doesn't work

### ISSUE THREAD

**Issue by vadim-hleif** [hairyhenderson/gomplate#370]
### Works
 type of content  the same as in `Content-Type` response header:
* `gomplate -d config=http://private-30833-vadimhleif.apiary-mock.com/yaml  -i '{{ (ds "config").name }}'`
### Don't work
 type of content  not the same as in `Content-Type` response header, overriding MIME doesn't work:
* `gomplate -d config=http://private-30833-vadimhleif.apiary-mock.com/text   -i '{{ (ds "config").name }}'` don't work, expected
* `gomplate -d config=http://private-30833-vadimhleif.apiary-mock.com/text?type=application/yaml   -dicofnig=s "config").name }}'` don't work, not expected

![capture](https://user-images.githubusercontent.com/11632146/44151705-07157cee-a0ac-11e8-92f8-c894e37558a2.PNG)

### what
It may be helpful. for example, for github api: 
* `https://raw.githubusercontent.com/cloudposse/geodesic/master/README.yaml`
### why
* Github return resource with `text/plain` content-Type and gomplate can't parse yaml

### references
- https://gomplate.hairyhenderson.ca/datasources/#mime-types
- https://github.com/cloudposse/build-harness/issues/87

**Comment by hairyhenderson** [comment]
Hi @vadim-hleif, thanks for reporting this! I can confirm this behaviour, and based on how I wrote it, it makes sense - the URL query string gets parsed long before the `Content-Type` header is seen, so in effect, the `Content-Type` header always overrides anything provided in the URL.

I'd tend to agree with you that it's a bug, since the express purpose of the `?type=application/yaml` query string is to force the type.

My initial feeling on precedence is: path extension, `Content-Type` header, then finally, `type` query. 

This wouldn't help you in the case of the GitHub URL provided, since the `Content-Type` would still take precedence over the path extension. That being said, the `raw.githubusercontent.com` host will only return `text/plain` for non-binary files, which I seem to recall is by design (but can't find the reference right now)...

An option in the GitHub case is to use their contents API. It's a bit of a kludge but it's more predictable:

```
$ gomplate -d gh=https://api.github.com/repos/cloudposse/geodesic/contents/README.yaml -i '{{ ((ds "gh").content | base64.Decode | data.YAML).name }}'
Geodesic
```

Either way, `?type` should have precedence over `Content-Type`, so I'll fix that.

**Comment by vadim-hleif** [comment]
@hairyhenderson Hello, could you release this changes soon? Thank you!

**Comment by hairyhenderson** [comment]
My apologies @vadim-hleif! I'll see if I can get a release out today or this weekend.
