### ISSUE TITLE
Support for aws ssm in recursive mode

### ISSUE THREAD

**Issue by fhenri** [hairyhenderson/gomplate#427]
Hi,

Following Pull Request https://github.com/hairyhenderson/gomplate/pull/248, we can get the value of a parameter but its not possible to use a recursive mode 

Its been proposed in the comment https://github.com/hairyhenderson/gomplate/pull/248#issuecomment-362522729 to use a second argument which look neat

Path including merged 2nd arg like readVault | Method | Description
-- | -- | --
somepath | GetParameter | Simple case, maybe 3rd arg to be a default if absent (otherwise error)
somepath?mode=one-level | GetParametersByPath (non-recursive) | Get a single hierarchy level's params, no 3rd arg
somepath?mode=recursive | GetParametersByPath (recursive) | Get a whole hierarchy's params, no 3rd arg

It will be awesome to have something like this - When using recursive mode, values will be returned through an array which we could loop using the `range` method

Kind regards,
Fred

**Comment by nenych** [comment]
Hello,
Is there any update on this issue? I know a lot of people who really like the gomplate but not using it because there is no possibility for the easy template creation.

**Comment by hairyhenderson** [comment]
Hi @nenych, no there's no update on this issue yet. I'm not sure about the `?mode` argument as that still seems awkward to me.

Since the initial support for the `aws+smp` datasource was added, gomplate gained support for [directory datasources](https://docs.gomplate.ca/datasources/#directory-datasources), and it feels like this would fit well into that model.

As a directory datasource, the way this would work would be with a URL like `aws+smp://path/to/secrets/`, and the `/` would trigger directory semantics (just like all the other datasources that support these semantics).

In the original issue, there was an open question about recursive vs non-recursive iteration; my gut feeling is that with directory datasource semantics this should always be non-recursive. If there's no need for the recursive mode, then this issue is ready to be implemented, but otherwise we need to figure out a way to work through this.

> I know a lot of people who really like the gomplate but not using it because there is no possibility for the easy template creation.

Are you saying that this issue in particular is preventing people from using gomplate? Or are you referring to something else? If so, please log a separate issue.

**Comment by hairyhenderson** [comment]
> with directory datasource semantics this should always be non-recursive

Thinking about this for a minute, I think having some way to recursively walk directories at a datasource level is probably useful.

Right now recursively walking through even `file:///` datasources is a pain and requires use of `file.ReadDir` (or `file.Walk`).

Perhaps a general `recursive=true` query parameter would work.
