### ISSUE TITLE
Render an inline template to a string

### ISSUE THREAD

**Issue by mkjpryor-stfc** [hairyhenderson/gomplate#444]
I may be missing it in the documentation, but a function that behaves like Helm's `include` would be great, i.e. rendering inline templates to a string that can be used in a pipeline.

E.g.

```
{{- define "greet" }}
{{ index . 0 }}: {{ index . 1 }}
{{- end }}

{{ template "greet" (list "hello" "Me") }}

greetings:
{{ include "greet" (list "hello" "You") | indent 2 }}
{{ include "greet" (list "hi" "Everyone!") | indent 2 }}
```

This would produce:

```
hello: Me

greetings:
  hello: You
  hi: Everyone!
```

Again, apologies if this already exists!

**Comment by mkjpryor-stfc** [comment]
Obviously the need for this is greater when templates are multi-line.

**Comment by hairyhenderson** [comment]
Hi @mkjpryor-stfc! Thanks for taking the time to file this!

gomplate has an `include` function, but it doesn't behave like this at all 😉

There's also the [`tpl`](https://gomplate.hairyhenderson.ca/functions/other/#tpl) function, but I don't think that's what you're looking for either.

It sounds like this is definitely something gomplate could use - obviously it can't be called `include` since that's taken already - any thoughts on what it should be named? Maybe `printTemplate` or `templateToString` or `tplToString`?

**Comment by hairyhenderson** [comment]
🤔 I like `<module>.TemplateToString` - was just thinking it probably belongs in a `templates` module or something... `tpl2str` would be OK - I'm not too sure about `render` though, a little too abstract.

Another possibility is to overload `tpl` - it already takes a template name as the optional first argument... I'll play around with that to see if it's even possible 😉

**Comment by mkjpryor-stfc** [comment]
Overloading `tpl` sounds like it could be confusing...

**Comment by hairyhenderson** [comment]
yeah, true... I'll play around with a few options and see what seems best 🙂

**Comment by hairyhenderson** [comment]
@mkjpryor-stfc I've implemented a new `tmpl.Exec` function that acts just like helm's `include` - let me know how it works for you. It's documented here: https://gomplate.hairyhenderson.ca/functions/tmpl/#tmpl-exec
