### ISSUE TITLE
keys are not sorted with range over maps

### ISSUE THREAD

**Issue by Josh-West-Bose** [hairyhenderson/gomplate#457]
Hi!

It looks like that when one uses `range` over a map, the resulting order is randomized.  Golang template says it is able to sort the results by key if the keys are comparable (such as with strings); I'm guessing that they're not comparable when being read in from a datasource such as a file with mimetype yaml?

Here's an example:

```
$ cat template
aws_zones                  = {
  {{- range $key, $value := (ds "core").cloud.aws.zones }}
  {{ $key }} = "{{ $value }}"
  {{- end }}
}

$ cat core.yaml
cloud:
  aws:
    zones:
      zonea: true
      zoneb: true
      zonec: true
      zoned: false
      zonee: false
      zonef: false
```

the output from `gomplate` seems to somewhat-randomize the ordering of the keys:

```
aws_zones                  = {
  zoneb = "true"
  zonec = "true"
  zoned = "false"
  zonee = "false"
  zonef = "false"
  zonea = "true"
}
```
with the order changing each time `gomplate` is run.

For reference, this is `gomplate_linux-amd64` version 3.1.0

**Comment by hairyhenderson** [comment]
Thanks for logging this, @Josh-West-Bose!

By default maps in Go are not sorted (and are actually actively randomized), but you're right about templates:

> If the value is a map and the keys are of basic type with a defined order ("comparable"), the elements will be visited in sorted key order.
>
> _https://golang.org/pkg/text/template/_

At first blush, it seems like YAML datasources _should_ be sortable, as they're unmarshaled as `map[string]interface{}`s. But that doesn't appear to be the whole story. YAML can have keys of many other potentially non-comparable types, so the above effectively falls apart.

Now, gomplate only supports YAML objects with `string` keys, so it would make sense to sort the map. I'll get this implemented over the next few days!

**Comment by hairyhenderson** [comment]
I did a bit more digging into this, and managed to reproduce it in a test case. The main issue is indeed due to key type, but it's a bit more subtle - the root of the datasource is a `map[string]interface{}` which _is_ sortable, but in your example, there would be one key `cloud` which would then contain a value that's determined to be a `map[interface{}]interface{}` (which is not sortable).

This is the point where Go's strict static typing gets in the way of what we're trying to accomplish 😂

I'm going to try to see if I can hack my way around this, but hopefully I can avoid re-implementing a YAML parser 😱...

**Comment by hairyhenderson** [comment]
Some progress - here's an issue on `gopkg.in/yaml.v2` that discusses (and contains multiple workarounds for) the problem: https://github.com/go-yaml/yaml/issues/139

I've forked and patched it for the time being, and a PR that uses it is incoming... 🎉
