### ISSUE TITLE
Need --include flag for opposite of --exclude

### ISSUE THREAD

**Issue by dorsany** [hairyhenderson/gomplate#540]
I want to include from my ```--input-dir``` only *.yml or *.yaml files

I saw that you support the flag of ```--exclude```
but I couldn't find a flag to support ```--include```

@hairyhenderson  , can you please assist me of how to handle this kind of situation?

Thanks!

**Comment by hairyhenderson** [comment]
Hi @dorsany! Thanks for logging this. In theory you should be able to use a negative exclusion since it's basically `.gitignore` format. But I tested it out, and can't get it to work.

This should (but doesn't) work:

```console
$ gomplate --exclude '!*.yml' --exclude '!*.yaml' --input-dir in/ ...
```

It looks like the library (https://github.com/zealic/xignore) package doesn't properly support `!` in this way.

Either way that'd be pretty awkward on the commandline! I think `--include` should definitely be supported for this kind of case 🙂

**Comment by dorsany** [comment]
Hi @hairyhenderson ,
Thank you for your help!

So what I did to exclude all except ```yml``` or ```yaml``` was:
```
gomplate --exclude '*' --exclude '!*.yml' --exclude '!*.yaml'  --input-dir ....
```
I think that you can close this case

**Comment by hairyhenderson** [comment]
@dorsany ah! I didn't try `--exclude '*'` - good to know 😉

I'd like to keep this open still, if you don't mind - a proper `--include` would be far more user-friendly!

**Comment by estahn** [comment]
I would like to see `--include` as well. But now I have a workaround with `--exclude` :)

**Comment by hairyhenderson** [comment]
Forgot about this one! Implemented in https://github.com/hairyhenderson/gomplate/pull/586.
