### ISSUE TITLE
Switch from dep to go mod

### ISSUE THREAD

**Issue by nexeck** [hairyhenderson/gomplate#545]
Is there a plan to switch from dep to go mod?

**Comment by hairyhenderson** [comment]
Not _explicitly_... I've been experimenting with go modules a bit in some of my other projects, and I honestly haven't been 100% comfortable with the state of modules yet. Mostly it's due to how I vendor dependencies, which isn't as easy with modules as it is with dep. Now that there's https://proxy.golang.org it's not such a big deal, but it's going to take some time for me to fully move over.

Is there a particular reason this would be important to you?

Either way I'm not saying "no", just "not yet" 😉

**Comment by nexeck** [comment]
I just had problems getting the dev setup running locally. Its long ago that i have worked with go dep :-)
Its more that i like the idea to have the project in the same directory structure like all other projecgts.

But in the End, it is not a show stopper for me :-)

**Comment by hairyhenderson** [comment]
Ah, so it was because of `$GOPATH` essentially? I totally understand that 😉

I put all my projects in `$GOPATH/src/<repo name>` regardless of whether it's a Go project or not, so moving to Go modules which _complains_ about being in `$GOPATH` is a hassle 😉

**Comment by mumoshu** [comment]
Hey! Commenting on this thinking I'm encountering an issue that relates to this.

I'm trying to use gomplate as a go library and encountering this due to how go mod works:

```
$ cat main.go
package main

import (
        "fmt"
        "github.com/hairyhenderson/gomplate/data"
        "os"
        "text/template"
)

func main() {
        dsName := "config"
        dsDef := fmt.Sprintf("%s=./config.yaml", dsName)
        datasources := []string{dsDef}
        datasourceHeaders := []string{}
        data, err := data.NewData(datasources, datasourceHeaders)
        if err != nil {
                fmt.Fprintf(os.Stderr, "%v\n", err)
                os.Exit(1)
        }
        tmpl := template.New("tmpl")
        tmpl, err = tmpl.Parse("a.b.c={{ .a.b.c }}")
        if err != nil {
                fmt.Fprintf(os.Stderr, "parse: %v\n", err)
                os.Exit(1)
        }
        ds, err := data.Datasource(dsName)
        if err != nil {
                fmt.Fprintf(os.Stderr, "datasource: %v\n", err)
                os.Exit(10)
        }
        if err := tmpl.Execute(os.Stdout, ds); err != nil {
                fmt.Fprintf(os.Stderr, "%v\n", err)
                os.Exit(1)
        }
}
```
```
$ go build .
go: gopkg.in/hairyhenderson/yaml.v2@v2.2.2: parsing go.mod: unexpected module path "gopkg.in/yaml.v2"
```

Reading the error log, this seems to be happening due to your fork of go-yaml has mismatching [module name(=gopkg.in/yaml.v2)](https://github.com/hairyhenderson/yaml/blob/v2/go.mod#L1) and the import(=gopkg.in/hairyhenderson/yaml). This builds fine with `dep`, but not with go modules.

// Probably fixing your fork's `go.mod` to have `gopkg.in/hairyhenderson/yaml.v2` and changing all the `gopkg.in/yaml.v2` reference in gomplate's code to `gopkg.in/hairyhenderson/yaml.v2` fixes that. But that's out of scope of this issue.

Not saying `go mod` is a must-have due to this. But switching gomplate itself to go modules does seem to help users like me, by ensuring gomplate trivial to be used from a go-mod based project :)

**Comment by mumoshu** [comment]
Also see this: https://github.com/mikefarah/yq/issues/197

**Comment by hairyhenderson** [comment]
@mumoshu Ah yes - my go-yaml fork was never supposed to last very long 😂 - though now that `yaml.v3` is out, it _may_ no longer be necessary.

Either way, there is a workaround for this that doesn't require gomplate to use go modules: 

You should be able to add a line like this to the end of your `go.mod`:

```
replace gopkg.in/yaml.v2 => github.com/hairyhenderson/yaml
```

See https://github.com/hairyhenderson/yaml/pull/1#issuecomment-482582795 for some discussion on this.

That being said, I've been using go modules in other projects with slightly better success, and it _may_ be time to migrate gomplate at some point soon...

**Comment by fatih** [comment]
Is there any ETA on moving to Go modules?

**Comment by hairyhenderson** [comment]
@fatih there isn't a specific ETA, though the more people ask for it the more likely I am to get around to it 😉

Are you asking for a specific reason?

**Comment by fatih** [comment]
Hey @hairyhenderson. It's not working with Go v1.13, even if I go and replace your fork with a replace directive. Doing a simple `go get ..` fails on this project. Also Go modules is by default enabled with the latest Go versions so it makes sense to support it.

**Comment by hairyhenderson** [comment]
@fatih hmm... yeah, I see the failures now. Seems that in a couple places I also imported `gopkg.in/hairyhenderson/yaml.v2` which is ... misbehaving 😂

I'll work on moving to modules today!

**Comment by hairyhenderson** [comment]
@fatih hey - I've gotten rid of my `gopkg.in/yaml.v2` fork in favour of upgrading to `gopkg.in/yaml.v3`, so hopefully `go get ./...` is a whole lot more reliable now. The move to modules is coming next, hopefully over the next day or two, time permitting.

**Comment by fatih** [comment]
Thank you @hairyhenderson this is a great step forward. It'll make it easier to move forward using Go modules as well :)

**Comment by hairyhenderson** [comment]
Ok! Sorry this took _so long_ to complete, but gomplate is finally switched over to go modules. I won't say it was _painless_, but it had the side-effect of forcing me to do a couple of outstanding upgrades I'd been stalling on 😉
