### ISSUE TITLE
Provide interface for adding custom functions

### ISSUE THREAD

**Issue by aescaler-a0d** [hairyhenderson/gomplate#551]
Functions can be exported to templates via template.FuncMap
It would be extremely useful to be able to define custom functions that are able to be utilized by a template on the fly.

I will be taking a look at the source when I'm not at work to see how difficult it would be for me to implement this in the current codebase, and provided I don't find it too difficult, will submit a pull request with the requisite changes.

**Comment by hairyhenderson** [comment]
Hi @angelofdeauth, thanks for logging this!

If you're talking about adding functions while calling gomplate programatically,  yes absolutely this would be a good idea.

Perhaps altering [`gomplate.Funcs`](https://github.com/hairyhenderson/gomplate/blob/master/funcs.go#L11) to also add some sort of custom function registry would do the trick.

A bigger issue is that calling gomplate programatically is awkward right now, and there's a bit of redesign that I'm working on to make that easier - that's tracked in #548. You may want to hold off until that's resolved since the API will likely have to change.

**Comment by angelofdeauth** [comment]
Yeah, I'll keep an eye on #548 for sure, maybe add my $.02 as well since I'm a fair user of both gomplate and helmfile

**Comment by hairyhenderson** [comment]
@angelofdeauth awesome! It's good to hear that gomplate's been useful for you! 😊

**Comment by hairyhenderson** [comment]
This will be possible with the new `Renderer` API added in #1422. The [`gomplate.Options`](https://pkg.go.dev/github.com/hairyhenderson/gomplate/v3#Options) struct has a `Funcs` field for adding custom functions programatically.

**Comment by iamFrancescoFerro** [comment]
Is there doc for this ?

**Comment by hairyhenderson** [comment]
@iamFrancescoFerro yes - see the Go documentation that I linked in the last comment I made.

**Comment by iamFrancescoFerro** [comment]
Oh ok but this by code, is there a way to use custom function using the `gomplate` binary ?

**Comment by hairyhenderson** [comment]
@iamFrancescoFerro for that you want https://docs.gomplate.ca/usage/#--plugin - if you have other questions please direct them to [Discussions](https://github.com/hairyhenderson/gomplate/discussions). This is a closed issue so is not the best place to communicate 😉
