### ISSUE TITLE
How to access elements in JSON object returned by datasource which is an array

### ISSUE THREAD

**Issue by loque1** [hairyhenderson/gomplate#573]
Hi I have a question. 

I am trying to access ECS metadata as a json datasource I can access not complex JSON data fine but when I want to access more complex data in the json data source like an array that contains a json array like 
```
"PortMappings": [
                {
                        "ContainerPort": 80,
                        "HostPort": 32788,
                        "BindIp": "0.0.0.0",
                        "Protocol": "tcp"
                }
        ],
"Networks": [
                {
                        "NetworkMode": "bridge",
                        "IPv4Addresses": [
                                "172.17.0.3"
                        ]
                }
        ],

```
how do I access IPV4Addresses.

I know 
`gomplate -d aws=metadata.json -i 'Hello {{ index (( datasource "aws").Networks) }}'`
this returns 
 `[map[IPv4Addresses:[172.17.0.3] NetworkMode:bridge]]`
How do I get just the value for IPv4Addresses. 
since the return was a map I though I could just use the '.' operator to access the element but that fails with 
`can't evaluate field IPv4Addresses in type []interface {} `
using 
`gomplate -d aws=metadata.json -i 'Hello {{ (( datasource "aws").Networks) | data.JsonArray }}'`
I get the following error
`can't evaluate field JsonArray in type *funcs.DataFuncs`

Any idea what I need to do to make this work?

**Comment by hairyhenderson** [comment]
Hi @loque1, thanks for logging this!

There's a few ways to achieve what you're looking for. One option is to `range` through each of the arrays, like this:

```console
$ gomplate -d aws=metadata.json -i 'Hello {{ range (datasource "aws").Networks }}{{ range .IPv4Addresses }}{{ . }}{{ end }}{{ end }}'
Hello 172.17.0.3
```

it's pretty verbose, but is probably what I'd usually do...

Another option is to use the [`coll.JSONPath`/`jsonpath`](https://docs.gomplate.ca/functions/coll/#coll-jsonpath) function:

```console:
$ gomplate -d aws=metadata.json -i 'Hello {{ (datasource "aws").Networks | jsonpath "$[*].IPv4Addresses[*]" }}'
Hello 172.17.0.3
```

It's a bit more complicated, especially since the JSONPath syntax is not always straightforward. But, if you need to traverse a _really_ tricky object it can sometimes be more compact.

Hope this helps!

**Comment by loque1** [comment]
Hi, 

Great  just what I was looking for. 

Thanks for the great tool
