### ISSUE TITLE
How to render bash arrays in templates

### ISSUE THREAD

**Issue by loque1** [hairyhenderson/gomplate#574]
Hi 
If I have an array defined in bash like 
`export SUBNETS=(112.111.124.1 123.124.125.2)`
and I want to use it in a template how can I do that. i have tried
 gomplate --verbose -d test=<(${SUBNETS}) -i '{{ range slice (datasource "test" ) }} {{ . }} {{ end }}'
which does not work. Is this even possible ?

**Comment by hairyhenderson** [comment]
Hi @loque1, this is definitely possible, but you'll need to do some mangling in your bash due to how bash arrays work - they're not environment variables, so you have to first convert them.

You could try something like:

_`foo.sh`:_
```bash
#!/bin/bash

export SUBNETS=(112.111.124.1 123.124.125.2)

# Convert to a colon-separated list
export SUBNETS_STR=$( IFS=:; printf '%s' "${SUBNETS[*]}" )

gomplate -i '{{ $subnets := getenv "SUBNETS_STR" | strings.Split ":" -}}
{{ range $subnets }}
Found subnet {{ . }}
{{ end }}'
```

```console
$ ./foo.sh
Found subnet 112.111.124.1
Found subnet 123.124.125.2
```

See https://unix.stackexchange.com/questions/393091/unable-to-use-an-array-as-environment-variable for some more discussion.

Also, for accessing environment variables you have the option of using `getenv`, or you can use the `env://` datasource - see https://docs.gomplate.ca/datasources/#using-env-datasources for the docs for that.

And one minor tip - instead of using `-d` you can use `-c` ([`--context`](https://docs.gomplate.ca/usage/#context-c)), which is exactly the same, except you don't need to use the `datasource` (or `ds`) function:

```bash
gomplate -c subs=env:///SUBNETS_STR -i '{{ $subnets := .subs | strings.Split ":" -}}
{{ range $subnets -}}
Found subnet {{ . }}
{{ end }}'
```

**Comment by loque1** [comment]
Hi 

Thanks for the code.  I modified it for my need like below 
echo $(printf '%q ' ${test[*]}) |  gomplate --verbose -c subnets=stdin:/// -i '{{ range .subnets | strings.Split " " }}
test {{ . }}
{{ end }} '
Keep up the great work :)

**Comment by hairyhenderson** [comment]
Thanks, glad to hear it worked for you @loque1!
