### ISSUE TITLE
Slim dependency tree

### ISSUE THREAD

**Issue by mcandre** [hairyhenderson/gomplate#675]
Hi,

gomplate seems to have a large dependency tree, pulling in strange things like the AWS SDK. Could we trim down the dependencies to just things dealing with YAML mapping?

**Comment by hairyhenderson** [comment]
Hi @mcandre! I agree, the dependency tree is large (and some might say - _out of control_). However, pulling in the AWS SDK is by design - there are AWS-related functions.

gomplate is a pretty wide-scoped tool, so necessarily there's going to be lots of dependencies. And once v3.6.0 drops the number of dependencies will be even larger 😉

What do you mean specifically by "YAML mapping?" What's your use-case?

**Comment by hairyhenderson** [comment]
@mcandre since I haven't heard anything for over a month I'm going to close this for now. If you feel strongly about this you're certainly welcome to re-open and make suggestions!
