### ISSUE TITLE
Gomplate ends in segfault when running in docker on L212 Dual-core ARM Cortex-A15 CPU

### ISSUE THREAD

**Issue by JKawohl** [hairyhenderson/gomplate#821]
Steps to reproduce:

1. Start alpine container on a QNAP with this CPU: L212 Dual-core ARM Cortex-A15 CPU
2. add gomplate via https://github.com/hairyhenderson/gomplate/releases/download/v3.6.0/gomplate_linux-arm
or 
https://github.com/hairyhenderson/gomplate/releases/download/v3.6.0/gomplate_linux-arm-slim
3. start gomplate in the container ./gomplate --version
4. Ends in segfault

At the same time when I  build a new container and add: 

COPY --from=hairyhenderson/gomplate:latest /gomplate /usr/bin/gomplate

Everything works fine and I can use gomplate. 
Am I using the wrong release? 

@geraldleikam FYI

**Comment by hairyhenderson** [comment]
@JKawohl thanks for logging this! This is actually quite timely, because last night I was attempting to do (almost) the same thing on a Raspberry Pi 3B+, and also seeing segfaults.

The non-versioned docker image tags (`:latest`, `:alpine`, and `:slim`) track the `master` branch, and so are generally much more recent. In this case, I updated last night (with #818) and that seems to be working now.

For now, you could continue using the binaries in the docker images. Note that the `slim` version is much slower to start on ARM, so you may want to stick with the larger binary.

This should be resolved with the next release of gomplate (hopefully coming soon!), so I'll close this now, but feel free to reopen if you need some other solution!
