### ISSUE TITLE
How to do dynamic datasource?

### ISSUE THREAD

**Issue by rayjlinden** [hairyhenderson/gomplate#828]
I have this template:
```
{{ define "lambda" }}
{{ defineDatasource "{{ .lambdaName }}-ds" "dockerfiles/{{ .lambdaName }}/{{ .lambdaName }}.env" -}}
resource "aws_lambda_function" "{{ .lambdaName }}" {
  function_name = "{{ .lambdaName }}"
  filename      = "{{ .lambdaName }}.zip"
  role          = "fake_role"
  handler       = "{{ .lambdaName }}"
  runtime       = "go1.x"
  timeout       = 30
  environment {
    variables = {
{{ include "{{ .lambdaName }}-ds" }}
    }
  }
}
{{ end }}

{{- range $repo, $repo_data :=  (datasource "data").repos }}
    {{- if $repo_data }}
        {{- if (has $repo_data "lambdas") }}
          {{- range $lam := $repo_data.lambdas}}
            {{- $ctx := dict "lambdaName" $lam "repo" $repo }}
            {{- template "lambda" $ctx }}
          {{- end }}
        {{- end}}
    {{- end}}
{{- end }}
```

I'm trying to create a bunch of lambda definitions from a data source.  But each lambda its one .env file I need to include in the definition.  Was hoping the above would work.  However, I get this error:
executing "lambda" at <include "{{ .lambdaName }}-ds">: error calling include: Couldn't read datasource '{{ .lambdaName }}-ds': Can't stat /var/tmp/rayj/gocode/src/github.com/lindenlab/extraction-makeworld/dockerfiles/{{ .lambdaName }}/{{ .lambdaName }}.env: stat /var/tmp/rayj/gocode/src/github.com/lindenlab/extraction-makeworld/dockerfiles/{{ .lambdaName }}/{{ .lambdaName }}.env: no such file or directory

How can I accomplish this?

**Comment by hairyhenderson** [comment]
Hi @rayjlinden!

Arguments to template functions aren't themselves templated, so you can't include templated strings like this:

```
{{ defineDatasource "{{ .lambdaName }}-ds" "dockerfiles/{{ .lambdaName }}/{{ .lambdaName }}.env" -}}
```

However, instead you can use `print` or `printf` to accomplish what you're looking for:

```
{{ defineDatasource (print .lambdaName "-ds") (print "dockerfiles/" .lambdaName "/" .lambdaName ".env") -}}
```

Or, slightly better with [`path.Join`](https://docs.gomplate.ca/functions/path/#path-join):

```
{{ defineDatasource (print .lambdaName "-ds") (path.Join "dockerfiles" .lambdaName (print .lambdaName ".env") -}}
```

Though maybe `printf` is a little simpler to grok:

```
{{ defineDatasource (printf "%s-ds" .lambdaName) (printf "dockerfiles/%s/%s.env" .lambdaName .lambdaName) -}}
```

However, if your goal is to simply include the file contents verbatim, you may find [`file.Read`](https://docs.gomplate.ca/functions/file/#file-read) a bit simpler:

```
{{ define "lambda" }}
{{ $envVars := file.Read (printf "dockerfiles/%s/%s.env" .lambdaName .lambdaName) -}}
resource "aws_lambda_function" "{{ .lambdaName }}" {
  function_name = "{{ .lambdaName }}"
  filename      = "{{ .lambdaName }}.zip"
  role          = "fake_role"
  handler       = "{{ .lambdaName }}"
  runtime       = "go1.x"
  timeout       = 30
  environment {
    variables = {
{{ $envVars | strings.Indent 6 }}
    }
  }
}
{{ end }}

{{- range $repo, $repo_data :=  (datasource "data").repos }}
    {{- if $repo_data }}
        {{- if (has $repo_data "lambdas") }}
          {{- range $lam := $repo_data.lambdas}}
            {{- $ctx := dict "lambdaName" $lam "repo" $repo }}
            {{- template "lambda" $ctx }}
          {{- end }}
        {{- end}}
    {{- end}}
{{- end }}
```

Here I've also used [`strings.Indent`](https://docs.gomplate.ca/functions/strings/#strings-indent) to make the file contents nicely indented. Maybe not necessary, but it's an option 😉

I'll close this now since I believe I've answered this, but feel free to follow up if you have more questions!

**Comment by rayjlinden** [comment]
Only follow-up is a huge thank you!

Ray

**Comment by hairyhenderson** [comment]
You're very welcome, @rayjlinden! 😄
