### ISSUE TITLE
Can't assign variable conditionally

### ISSUE THREAD

**Issue by glensc** [hairyhenderson/gomplate#844]
So I found documentation about variables:
- https://docs.gomplate.ca/syntax/#variables

and hooray, started to create variables, and then found that variables are not created in conditions.

there should be definitely put something about that in the documentation, coming from other worlds (not goland, this is very unexpected).

```
{{ if 1 }}
{{- $w := "world" -}}
{{ else }}
{{- $w := "earth" -}}
{{ end }}

Hello, {{ print $w }}!
Goodbye, {{ print $w }}.
```

```
➔ gomplate< if.tpl
template: -:7: undefined variable "$w"
```

**Comment by hairyhenderson** [comment]
Variables are scoped, and so that particular example is defining two separate variables named `$w`, first inside the `if` scope, and next inside the `else` scope. Once the end of that scope is reached, that variable is no longer defined.

So if you define the variable first outside that scope, it will work:

```go
{{- $w := "" }}
{{- if 1 }}
{{- $w = "world" -}}
{{ else }}
{{- $w = "earth" -}}
{{ end -}}

Hello, {{ print $w }}!
Goodbye, {{ print $w }}.
```

```console
$ gomplate -f in.tpl
Hello, world!
Goodbye, world.
```

Definitely the variables section in the docs could be enhanced. For reference, variables are documented here in the Go `text/template` docs: https://golang.org/pkg/text/template/#hdr-Variables. I'll probably take some of that text and included in the gomplate docs!

**Comment by hairyhenderson** [comment]
Documented in #845

**Comment by glensc** [comment]
YEah, I figured it's some pitfall that needs to be documented, thanks for handling this!
