### ISSUE TITLE
--exclude does not work

### ISSUE THREAD

**Issue by jsirianni** [hairyhenderson/gomplate#877]
My templates directory contains a file: `data.template.yaml`. I wish to render all templates except this file.

My command
```sh
gomplate \
    -d config=config.yaml\
    --exclude=templates/data.template.yaml \
    --input-dir=templates \
    --output-dir=temp/configs
```

Error
```sh
17:28:00 FTL  error="template: templates/data.template.yaml:2:26: executing \"templates/data.template.yaml\" at <.Env.NAME>: map has no entry for key \"NAME\""
```

The error is correct, `NAME` does not exist in the environment. I would expect gomplate to skip this file because of the `--exclude` flag. If I set NAME in my environment, gomplate works fine.

version
```
❯ gomplate --version
gomplate version 3.7.0
```

macos version
```
10.15.3 Catalina
```

Am I doing something wrong? Thanks!

**Comment by hairyhenderson** [comment]
Hi @jsirianni, thanks for logging this!

Yeah, as noted in [the docs for `--exclude`](https://docs.gomplate.ca/usage/#exclude-and-include), the pattern is matched relative to the input directory, which in your case is `templates`, so this should work:

```console
$ gomplate \
    -d config=config.yaml\
    --exclude=data.template.yaml \
    --input-dir=templates \
    --output-dir=temp/configs
```

I'll close this for now because I believe that'll fix it for you, but if you have further issues or this isn't working for you, feel free to re-open!
