### ISSUE TITLE
Advice on generating JS config file from YAML/JSON datasource

### ISSUE THREAD

**Issue by asterikx** [hairyhenderson/gomplate#898]
I need to generate runtime config files for my single-page application. Currently I have:

Template file:
```
module.exports = {
  {{- range $key, $value := (ds "config") }}{{ $key }}: {{ $value }},{{ end }}
};
```

Config file (YAML):
```
API_URL: 'https://staging.mydomain.com/api'
FEATURE_FLAG_X: false
```

... which generates:

```js
module.exports = {
 API_URL: https://staging.mydomain.com/api,
 FEATURE_FLAG_X: false,
}
```

However, this isn't valid JS (missing string quotes around `https://staging.mydomain.com/api`).

What I need:

```js
module.exports = {
 API_URL: 'https://staging.mydomain.com/api',
 FEATURE_FLAG_X: false,
}
```

Note that there should be no added string quotes for boolean values. Is it possible to preserve the string quotes from the config file?

I'm seeking some general advice. Thanks!

**Comment by hairyhenderson** [comment]
Hi @asterikx, thanks for posting this!

The challenge here is that in order to know whether to quote the `$value` or not, you need to know its type. You can use `printf "%T" $value` to determine the type, though #892 presents some ways to make that simpler.

However in this particular case, since JSON syntax is valid JS object syntax, you could simply convert to JSON:

```
module.exports = {{ ds "config" | toJSONPretty "  " }};'
```

That produces this output:

```js
module.exports = {
  "API_URL": "https://staging.mydomain.com/api",
  "FEATURE_FLAG_X": false
};
```

Assuming this answers the question, I'm going to close this, but feel free to follow up or re-open if you're looking for more help! Also if you like you can join the [Gophers Slack](https://invite.slack.golangbridge.org/) instance, where there's a `#gomplate` channel where some other gomplate users hang out and can help with questions like these.
