### ISSUE TITLE
Best way to deal with final empty line?

### ISSUE THREAD

**Issue by max-sixty** [hairyhenderson/gomplate#905]
Potentially this is a naive question, appreciate your understanding if so.

I'm mostly using gomplate to take a list of lines from a source and output a new list of lines. When I use gomplate to do this, I'm left with a final line based on an empty input.

For example, this script lists files in a bucket, and creates a bigquery command from each based on its name.

```sh
gsutil ls gs:/mybucket/mypath \
| gomplate -d data=stdin: -i '
{{ range ((ds "data") | strings.Split "\n") }}
bq load --source_format=PARQUET --replace my_dataset.table_prefix_{{ . | regexp.Replace `.*partition=([\w]+).*` "$1" }} \'{{ . }}*.parquet\'
{{ end }}'
```

Unfortunately the final item is always:
```
bq load --source_format=PARQUET --replace my_dataset.table_prefix_ '*.parquet'
```
...I think because gomplate splits the items based on `\n`, which includes the final item there.

I've added a `{{- if . -}}`, which prevents this, but makes the script longer & less obvious.

Is there an easier way / am I taking the wrong general approach here? 
Thanks!

**Comment by hairyhenderson** [comment]
Thanks for logging this @max-sixty. There's a couple of answers to this, depending on how general you want to be 😉

The first answer is that since you're just looking for a list of files in GCS, you can simply use [the `gs` datasource](https://docs.gomplate.ca/datasources/#using-google-cloud-storage-gs-datasources):

```console
$ gomplate -c files=gs://mybucket/mypath/ -i '{{ range .files }}
bq load --source-format=PARQUET --replace my_dataset.table_prefix_{{ . | regexp.Replace ...whatever }}...
{{ end }}
```

_Notes:_
- Consider using `-c` instead of `-d` - makes for simpler syntax, and can replace most uses of `-d`. See https://docs.gomplate.ca/usage/#context-c for details.
- The `/` at the end of the URL argument to `-c` is important - this triggers directory semantics
- I'm not understanding the regexp - I'll leave that up to you!
- When you find yourself having to escape single-quotes, it's often best to just put the template in a file where you don't have to worry about that

If you don't want gomplate to access the bucket, or if you have a more general "newline-separated list on stdin" use-case, you could simply use [`strings.TrimSpace`](https://docs.gomplate.ca/functions/strings/#strings-trimspace) on the input first:

```
{{ range (ds "data" | strings.TrimSpace | strings.Split "\n") }}
...
```

When dealing with datasources, however, I'd recommend using structured data instead of `stdin` whenever possible.

**Comment by max-sixty** [comment]
This works really well! Thank you for addressing my issue on so many levels. After incorporating the gs source, the others weren't necessary; hopefully others will find them helpful in the future though.

I'll close this issue

**Comment by max-sixty** [comment]
Could I ask where I'd see more docs on the `.files` you used above? It works great; I'm curious whether there's anything else I can use in the same place (e.g. the full path), and I couldn't find any documentation referencing `.files` in ~5 minutes of searching on the docs.

Thank you!

**Comment by hairyhenderson** [comment]
@max-sixty `.files` is referring to the `files` entry that's added to the context by the `-c files=...` argument. See https://docs.gomplate.ca/usage/#context-c and https://docs.gomplate.ca/syntax/#the-context for reference  on the context.

**Comment by max-sixty** [comment]
Perfect, that makes sense, thank you again @hairyhenderson !
