### ISSUE TITLE
Datasource to execute command and grab results

### ISSUE THREAD

**Issue by hongkongkiwi** [hairyhenderson/gomplate#964]
Feature request: 

I would like to execute a command or shell script and pull the output as a datasource.
ds="exec:///home/andy/myscript.sh?arg=hello&arg=world" this would be really helpful.

I can already do this with a environment variable e.g. OUTPUT=/home/andy/myscript.sh "hello" "world"; gomplate ....... 

However, having datasource would be much cleaner and extend the feature set a lot.

**Comment by hongkongkiwi** [comment]
I found the plugin feature, but it still doesn't seem to quite do what I want:

I want to interpret one item that's being passed to the plugin, in this case grab the value from an ENV and pass it to a plugin.....
```
gomplate --plugin awscli=/usr/local/bin/aws -i '{{ awscli "rds" "generate-db-auth-token" "--hostname" "{{ .Env HOSTNAME }}" "--port" 3306 "--region" "us-west-1" "--username" "test123" }}'
```

**Comment by hairyhenderson** [comment]
Hi @hongkongkiwi, yes `--plugin` is intended for this use-case, though I'm not quite sure what doesn't work for you. Maybe it's just a syntax thing...

How about:

```
$ gomplate --plugin awscli=/usr/local/bin/aws
  -i '{{ awscli "rds" "generate-db-auth-token" "--hostname" .Env.HOSTNAME "--port" "3306" "--region" "us-west-1" "--username" "test123" }}'
```

Basically, instead of wrapping `.Env.HOSTNAME` in a string template, just pass it as-is, since you're already in a template action. Just FYI, an alternative to using `.Env` is the `getenv` function, which lets you set a default. See https://docs.gomplate.ca/functions/env/#env-getenv for details.

I think this answers the question, though if not, please feel free to elaborate!

**Comment by hongkongkiwi** [comment]
Fantastic, very helpful! Thanks.
