### ISSUE TITLE
Use post-template result as args for external command

### ISSUE THREAD

**Issue by hongkongkiwi** [hairyhenderson/gomplate#968]
I've got a strange requirement. I need to pass the response from gomplate straight into another command as args....

Here's my example
```
gomplate -i '{{ range ("[\"foo\",\"bar\"]" | jsonArray) }}{{ . }}{{ end }}' -- myscript
```

In this case, what I want is to run something like this: `./myscript "foo" "bar"`

I've seen the --exec-pipe flag, but that pipes the output to the command, what I would like to do is use all output as input args.

Any ideas on this?

**Comment by hongkongkiwi** [comment]
Managed to solve my own problem with piping output to xargs :)

**Comment by hairyhenderson** [comment]
It could actually be pretty simple to implement an `--exec-with-args` flag 🤔

Alternatively, if it's a script you control, you could accept args through stdin instead.

I think I'll re-open this to look at an `--exec-with-args` flag 😉

**Comment by hairyhenderson** [comment]
I've (finally) dug into this for a little while, and it looks like this would be complex to implement correctly, and for very little real value. This is mostly because I'd need to deal with handling shell quoting (e.g. splitting up args correctly like `"foo bar" baz "qux \"quux\" \"\"\" corge"`).

As @hongkongkiwi mentioned, this is easily handled with `xargs`, for example:

```console
$ cat ./myscript.sh 
#!/bin/sh
echo "arg1 is $1"
echo "arg2 is $2"
$ gomplate -i '"foo" "bar"' --exec-pipe -- xargs ./myscript.sh 
arg1 is foo
arg2 is bar
```
