### ISSUE TITLE
Empty line in stderr starting with v3.7.0

### ISSUE THREAD

**Issue by lmakarov** [hairyhenderson/gomplate#996]
This is a minor issue that surfaced in our automated tests.

Starting with v3.7.0, gomplate started throwing an empty line into stderr output:

```
docker@cli:/var/www$ touch in.tmpl

# 3.6.0
docker@cli:/var/www$ ./gomplate --version
gomplate version 3.6.0
docker@cli:/var/www$ ./gomplate --file in.tmpl
docker@cli:/var/www$ 

# 3.7.0
docker@cli:/var/www$ ./gomplate --version
gomplate version 3.7.0
docker@cli:/var/www$ ./gomplate --file in.tmpl

docker@cli:/var/www$ ./gomplate --file in.tmpl 2>/dev/null
docker@cli:/var/www$ 
```

**Comment by hairyhenderson** [comment]
Hi @lmakarov yes, this is by design, though I apologize for not explicitly calling it out in the release notes. It came in as part of #692. The reason this is done now is simply to help the output look less awkward in certain cases where the printed output doesn't end with a newline, and then only on certain shells.

Other than the cosmetic effect, what's the negative impact to your tests?

I'm certainly open to adding some logic so that this is only done when the stdout stream doesn't end with a newline, though that would add complexity.

**Comment by lmakarov** [comment]
@hairyhenderson we use gomplate in a startup script for a container. That container may be used like a binary and the results from its output are then passed somewhere else. In that case, we get a rogue empty new line in the output coming from gomplate.

Its not a big deal. I've just muted the output from gomplate like this

```
gomplate --file "${tmpl}" --out "${file}" &>/dev/null
```

Though, that mutes ALL output, including possible errors which we'd ideally want to catch.

Not printing an empty line into stderr if `--out` is used would eliminate this issue.

**Comment by hairyhenderson** [comment]
@lmakarov ok, thanks for the feedback! That makes sense, and should be pretty easy to fix for you.

**Comment by CheyiLin** [comment]
Should it also cover the case when `--output-dir` is used? Just tried the latest `v3.9.0` it still prints the empty lines.

**Comment by hairyhenderson** [comment]
@CheyiLin I thought it did... But you could log a new issue if you're seeing it with v3.9.0. TBH the logic is pretty awkward, so I probably missed something! 😉
